version: '3'

networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge

services:
  app:
    build:
      context: ./
      dockerfile: vm/php/dev.dockerfile
    container_name: insta_app
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
      DB_PORT: 3306
      DB_HOST: database
    working_dir: /var/www
    volumes:
      - ./:/var/www
    networks:
      - backend
      - frontend

  web:
    build:
      context: ./
      dockerfile: vm/web/nginx.dockerfile
    container_name: insta_web
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: web
      SERVICE_TAGS: dev
    working_dir: /var/www
    volumes:
      - ./:/var/www
    networks:
      - frontend
    ports:
      - 8080:80

  database:
    image: mysql:5.7
    container_name: insta_db
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: db
      SERVICE_TAGS: dev
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - db_persist:/var/lib/mysql
    networks:
      - backend
    ports:
      - 33061:3306

volumes:
  db_persist:
    driver: local
